/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class walker_person_mediahandlerlib_video_natives_H264Decoder */

#ifndef _Included_walker_person_mediahandlerlib_video_natives_H264Decoder
#define _Included_walker_person_mediahandlerlib_video_natives_H264Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     walker_person_mediahandlerlib_video_natives_H264Decoder
 * Method:    initDecoder
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_walker_person_mediahandlerlib_video_natives_H264Decoder_initDecoder
  (JNIEnv *, jobject);

/*
 * Class:     walker_person_mediahandlerlib_video_h264_H264Decoder
 * Method:    consumeStream
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_walker_person_mediahandlerlib_video_natives_H264Decoder_consumeStream
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     walker_person_mediahandlerlib_video_h264_H264Decoder
 * Method:    releaseDecoder
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_walker_person_mediahandlerlib_video_natives_H264Decoder_releaseDecoder
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
