/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class walker_person_mediahandlerlib_example_Demux */

#ifndef _Included_walker_person_mediahandlerlib_example_Demux
#define _Included_walker_person_mediahandlerlib_example_Demux
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     walker_person_mediahandlerlib_example_Demux
 * Method:    initNativa
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_walker_person_mediahandlerlib_example_Demux_initNativa
  (JNIEnv *, jobject);

/*
 * Class:     walker_person_mediahandlerlib_example_Demux
 * Method:    demux
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT void JNICALL Java_walker_person_mediahandlerlib_example_Demux_demux
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
